name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
    - name: Restore
      run: dotnet restore --locked-mode
    - name: Build
      run: dotnet build --no-restore --nologo
    - name: Test
      run: dotnet test --no-build --verbosity normal
